version: '{build}'
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
nuget:
  disable_publish_on_pr: true
build_script:
- ps: PowerShell -Version 2.0 .\build.ps1
test: off
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet Package
- path: .\artifacts\**\*.trx
  name: Test Results
deploy:
  provider: NuGet
  api_key:
    secure: puUU4Nk2uNe4VVODI+iSkp7SQUuTCJkyli52A+fQhCXXFZEK9pMnMGat/1z7xnu2